display_name: FlClashX

packager: anchel
packagerEmail: anchel.xy@gmail.com
license: Other

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/icon.png

keywords:
  - FlClashX
  - Clash
  - ClashMeta
  - Proxy

generic_name: FlClashX

group: Applications/Internet

startup_notify: true