script_template: inno_setup.iss
app_id: C4409322-653F-448F-98F1-AF11CBC6FA50
app_name: FlClashX
publisher: anchel
publisher_url: https://github.com/anchel/FlClash
display_name: FlClashX
executable_name: FlClashX.exe
output_base_file_name: FlClashX.exe
setup_icon_file: ..\windows\runner\resources\app_icon.ico
locales:
  - lang: zh
    file: ..\windows\packaging\exe\ChineseSimplified.isl
  - lang: en
privileges_required: admin