script_template: inno_setup.iss
app_id: B328B152-86CE-4528-AF10-7C0088AC51F2
app_name: FlClashX
publisher: chen08209
publisher_url: https://github.com/chen08209/FlClash
display_name: FlClashX
executable_name: FlClashX.exe
output_base_file_name: FlClashX.exe
setup_icon_file: ..\windows\runner\resources\app_icon.ico
locales:
  - lang: zh
    file: ..\windows\packaging\exe\ChineseSimplified.isl
  - lang: en
privileges_required: admin